[package]
name = "cargo_test_formatter"
version = "0.4.0"
authors = ["Hmvp <github@hmvp.nl>", "Max Gortman <maxim.hortman@gmail.com>"]
edition="2018"

[dependencies]
RustyXML = "0.3"
nom = { version = "6.0" }
